In [1]:
import pandas as pd

In [19]:

df = pd.read_parquet("data/explore.parquet.gzip")
df["Source_Title"] = df["Source_Title"].apply(lambda x: str(x).replace("\n"," "))
df.Source = df.Source.apply(lambda x: str(x).strip(".").strip().strip(".").strip().strip(".").strip())
print(len(df.Source.unique()))

169

In [20]:
df

,FromProbono,Origin,Place,Type,Source,Justification,Purpose,Issue,Scale,Score,Justification_Short,Source_Title,Reviewed,model
0,True,D7.15,Brussels,Vision,## Objectives \nThe Brussels LL is unique with...,The text emphasizes the importance of neighbou...,Attractiveness,"Governance, empowerment and engagement",Neighbourhood,5,Neighbourhood engagement crucial for renovations,Emphasizing neighbourhood engagement and innov...,False,gpt-4o
1,True,D7.15,Brussels,Vision,## Objectives \nThe Brussels LL is unique with...,The Brussels Living Lab focuses on involving v...,Attractiveness,Culture and community identity,Neighbourhood,4,Fostering community through stakeholder collab...,Emphasizing neighbourhood engagement and innov...,False,gpt-4o
2,True,D7.15,Brussels,Vision,## Objectives \nThe Brussels LL is unique with...,The project's focus on collaborative and parti...,Social cohesion,"Living together, interdependence and mutuality",Neighbourhood,5,Promoting collaboration for cohesive communities.,Emphasizing neighbourhood engagement and innov...,False,gpt-4o
3,True,D7.15,Brussels,Vision,## Objectives \nThe Brussels LL is unique with...,The physical technologies and innovations like...,Well-being,Living and working environment,Building,4,Sustainable technologies enhance living enviro...,Emphasizing neighbourhood engagement and innov...,False,gpt-4o
4,True,D7.15,Brussels,Vision,## Objectives \nThe Brussels LL is unique with...,While safety and security are not the main foc...,Resilience,Safety and security,Building,3,Technologies enhance building energy resilience.,Emphasizing neighbourhood engagement and innov...,False,gpt-4o
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3510,True,D7.2,Prague,Vision,The vision of Prague Living Lab involves the d...,The text emphasizes the application of future ...,Responsible resource use,Education and capacity building,Building,4,None,Prague Living Lab: Green Building Neighbourhood.,True,None
3511,True,D7.2,Prague,Vision,The vision of Prague Living Lab involves the d...,The emphasis on engagement of citizens and the...,Social cohesion,"Governance, empowerment and engagement",Neighbourhood,4,None,Prague Living Lab: Green Building Neighbourhood.,True,None
3512,True,D7.2,Prague,Vision,The vision of Prague Living Lab involves the d...,The text mentions the consideration of natural...,Preservation and improvement of environment,Biodiversity and ecosystem services,Neighbourhood,3,None,Prague Living Lab: Green Building Neighbourhood.,True,None
3513,True,D2.3,Prague,Activities,The Climate Change Awareness Assessment survey...,The text emphasizes the preparation of a Clima...,Preservation and improvement of environment,Education and capacity building,Neighbourhood,4,None,Climate change survey for Prague University.,True,None
3514,True,D2.3,Prague,Activities,The Climate Change Awareness Assessment survey...,The survey aims to inform communication activi...,Resilience,"Innovation, creativity and research",Building,3,None,Climate change survey for Prague University.,True,None

In [31]:
DF = df[["Source","Origin","Place","Type"]].drop_duplicates()
DF = DF[DF.Type == "Activities"]
DF = DF[~DF.Origin.isin(["KERs file"])]
DF.groupby(["Origin","Place"]).count()

                     Source  Type
Origin     Place
D2.3       Aarhus         2     2
           Brussels       4     4
           Dublin         4     4
           Madrid         3     3
           Porto          4     4
           Prague         4     4
           Probono        2     2
D2.3_Cerna Probono        1     1
D5.1       Aarhus         5     5
           Brussels       8     8
           Dublin        16    16
           Madrid        10    10
           Porto          5     5
           Prague         4     4
           Probono        5     5
D7.12      Porto         18    18
D7.15      Brussels       4     4
D7.21      Prague         7     7
D7.6       Dublin         8     8
D7.9       Madrid         9     9
DLV37      Aarhus         1     1
           Probono        4     4
DLV38B     Aarhus         3     3
           Probono        2     2

In [38]:
DF[(DF.Origin == "D7.12") & (DF.Place == "Porto")].to_excel("data/IDs.xlsx")